// themes/bt4/src/components/Footer.jsx
import React from 'react';

const Widget = () => (
  <div className="container">
    <hr/>
    <footer>
      <p className="pull-right"><a href="#">Back to top</a></p>
      <p>&copy; 2016 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
  </div>
)

export default Widget

// frontend/src/components/Footer.vue
<template>
  <div class="container">
    <hr class="featurette-divider">
      <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
  </div>
</template>

<script>
export default {
  name: 'application-footer',
  data () {
    return {
    }
  }
}
</script>
