// themes/bt4/src/components/Header.jsx
import React, {PropTypes} from 'react';
import { Navbar, Nav, NavItem } from 'react-bootstrap';
import { connect } from 'react-redux'
import { Link } from 'react-router'
import i18next from 'i18next';
import {LinkContainer} from 'react-router-bootstrap'

import PersonalBar from './PersonalBar'
import LanguageBar from './LanguageBar'
import {DASHBOARD} from '../constants'
import engines from '../engines'

const Widget = ({info, user}) => (
  <Navbar fixedTop fluid inverse collapseOnSelect>
    <Navbar.Header>
      <Navbar.Brand>
        <Link to="/">{info.subTitle}</Link>
      </Navbar.Brand>
      <Navbar.Toggle />
    </Navbar.Header>
    <Navbar.Collapse>
      <Nav>
        <LinkContainer to='/home'>
          <NavItem>{i18next.t('header.home')}</NavItem>
        </LinkContainer>
        {
          engines.navLinks.map((l,i)=>(<LinkContainer key={i} to={l.href}>
            <NavItem>{i18next.t(l.label)}</NavItem>
          </LinkContainer>))
        }
        {
          user.uid ?
          (<LinkContainer to={DASHBOARD}>
            <NavItem>{i18next.t("header.dashboard")}</NavItem>
          </LinkContainer>) :
          "&nbsp;"
        }
      </Nav>
      <Nav pullRight>
        <LanguageBar/>
        <PersonalBar/>
      </Nav>
    </Navbar.Collapse>
  </Navbar>
)

Widget.propTypes = {
  info: PropTypes.object.isRequired,
  user: PropTypes.object.isRequired,
}

export default connect(
   state => ({info: state.siteInfo, user: state.currentUser})
)(Widget);

// frontend/src/components/Header.vue
<template>
  <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <router-link class="navbar-brand" :to="{name: 'home'}">
        {{ $t("site.subTitle") }}
      </router-link>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <router-link class="nav-link" :to="{name: 'home'}">
              {{ $t("header.home") }} <span class="sr-only">(current)</span>
            </router-link>
          </li>
          <li :key="l.href" v-for="l in links">
            <router-link class="nav-link" :to="{name: l.href}">{{ $t(l.label) }}</router-link>
          </li>
          <language-bar />
          <personal-bar />
        </ul>
        <search-form />
      </div>
    </nav>
</template>

<script>
import {links} from '@/engines'

import SearchForm from './SearchForm'
import PersonalBar from './PersonalBar'
import LanguageBar from './LanguageBar'

export default {
  name: 'application-header',
  data () {
    return {links}
  },
  components: {
    'search-form': SearchForm,
    'personal-bar': PersonalBar,
    'language-bar': LanguageBar
  },
  computed: {
    info () {
      return this.$store.state.siteInfo
    }
  }
}
</script>
