// themes/bt4/src/components/PersonalBar.jsx
import React,{Component, PropTypes} from 'react';
import { connect } from 'react-redux'
import {browserHistory} from 'react-router'
import { NavDropdown, MenuItem } from 'react-bootstrap';
import {LinkContainer} from 'react-router-bootstrap'
import i18next from 'i18next';

import {signOut} from '../actions'
import {DASHBOARD} from '../constants'

class Widget extends Component{
  constructor(props){
    super(props)
    this.state = {}
    this.handleSignOut = this.handleSignOut.bind(this);
  }
  handleSignOut(e) {
    if(confirm(i18next.t('are-you-sure'))){
      browserHistory.push('/')
      sessionStorage.clear();
      const {signOut} = this.props
      signOut()
    }
  }
  render(){
    const {user} = this.props
    return (
      user.uid ?
      <NavDropdown title={i18next.t("personal-bar.welcome", {name:user.name})} id="header-personal-bar">
        <LinkContainer to={DASHBOARD}>
          <MenuItem>{i18next.t("personal-bar.dashboard")}</MenuItem>
        </LinkContainer>
        <MenuItem divider />
        <MenuItem onClick={this.handleSignOut}>{i18next.t("personal-bar.sign-out")}</MenuItem>
      </NavDropdown> :
      <NavDropdown title={i18next.t("personal-bar.sign-in-or-up")} id="header-personal-bar">
        {['sign-in', 'sign-up', 'confirm', 'unlock', 'forgot-password'].map((k,i)=>(
          <LinkContainer key={i} to={`/users/${k}`}>
            <MenuItem>{i18next.t(`auth.users.${k}.title`)}</MenuItem>
          </LinkContainer>
        ))}
      </NavDropdown>
    )
  }
}

Widget.propTypes = {
  user: PropTypes.object.isRequired,
  signOut: PropTypes.func.isRequired
}

export default connect(
  state => ({user: state.currentUser}),
  {signOut},
)(Widget)

// frontend/src/components/PersonalBar.vue
<template>
  <li v-if="user.uid" class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="personal-bar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{$t("personal-bar.welcome", {name:user.name})}}
    </a>
    <div class="dropdown-menu" aria-labelledby="personal-bar">
      <router-link :to="{name: 'home'}" class="dropdown-item">{{$t("personal-bar.dashboard")}}</router-link>
      <div class="dropdown-divider"></div>
      <a v-on:click="onSignOut" class="dropdown-item">{{ $t("personal-bar.sign-out") }}</a>
    </div>
  </li>
  <li v-else class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="personal-bar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{$t("personal-bar.sign-in-or-up")}}
    </a>
    <div class="dropdown-menu" aria-labelledby="personal-bar">
      <router-link :key="a" :to="{name: `auth.users.${a}`}" class="dropdown-item" v-for="a in actions">
        {{$t(`auth.users.${a}.title`)}}
      </router-link>
      <router-link :to="{name: 'home'}" class="dropdown-item">{{$t("site.leave-words.new.title")}}</router-link>
    </div>
  </li>
</template>

<script>
import {TOKEN} from '@/constants'
import {_delete} from '@/ajax'

export default {
  name: 'personal-bar',
  data () {
    return {
      actions: ['sign-in', 'sign-up', 'forgot-password', 'confirm', 'unlock']
    }
  },
  beforeCreate () {
    var token = sessionStorage.getItem(TOKEN)
    if (token) {
      this.$store.commit('signIn', token)
    }
  },
  methods: {
    onSignOut () {
      _delete('/users/sign-out').then(function () {
        this.$store.commit('signOut')
        this.$router.push({ name: 'auth.users.sign-in' })
      }.bind(this))
    }
  },
  computed: {
    user () {
      return this.$store.state.currentUser
    }
  }
}
</script>
