// themes/bt4/src/engines/reading/books.jsx
import React, { Component } from 'react';
import i18next from 'i18next';
import {Pagination, Thumbnail, Button} from 'react-bootstrap';
import {LinkContainer} from 'react-router-bootstrap'


import {get} from '../../ajax'

const PAGE_SIZE = 60

export class Index extends Component{
  constructor(props){
    super(props)
    this.state = {
      page:1,
      size:PAGE_SIZE,
      total:0,
      count:1,
      items:[]
    }
    this.handleSelect = this.handleSelect.bind(this);
  }
  componentDidMount() {
      this.loadBooks(1, PAGE_SIZE)
  }
  handleSelect(page){
    this.loadBooks(page, PAGE_SIZE)
  }
  loadBooks(page, size){
    get(`/reading/books?size=${size}&page=${page}`).then(
      function(rst){
        this.setState(rst)
      }.bind(this)
    );
  }
  render(){
    var pager = (<div className="col-md-12">
      <Pagination
          prev
          next
          first
          last
          ellipsis
          boundaryLinks
          items={this.state.count}
          maxButtons={5}
          activePage={this.state.page}
          onSelect={this.handleSelect} />
      </div>)
    return (<div className="row">
      <h3>{i18next.t('reading.books.index.title')}</h3>
      <hr/>
      {pager}
      {this.state.items.map((b,i)=>(<div className="col-md-4" key={i}>
        <Thumbnail>
          <h3>{b.title}</h3>
          <p>{b.author}</p>
          <p>
            <LinkContainer to={`/reading/books/${b.id}`} target="_blank">
              <Button bsStyle="primary">{i18next.t('buttons.view')}</Button>
            </LinkContainer>
          </p>
        </Thumbnail>
      </div>))}
      {pager}
    </div>)
  }
}

export class Show extends Component{
  constructor(props){
    super(props)
    this.state = {
      book:{},
      home: ''
    }
  }
  componentDidMount() {
    const {params} = this.props
    get(`/reading/books/${params.id}`).then(
      function(rst){
        this.setState(rst)
      }.bind(this)
    );
  }
  render(){
    return (<div className="row">
      <h3>{this.state.book.title}-{this.state.book.author}</h3>
      <hr/>
      <p dangerouslySetInnerHTML={{__html: this.state.home}}></p>
    </div>)
  }
}

// frontend/src/engines/reading/books/Index.vue
<template>
  <application-layout>
    <h2>{{$t('reading.books.index.title')}}</h2>
    <hr/>
    <pagination-panel :item="pager" :href="{name: 'reading.books.pages'}"/>
    <div class="card-columns">
      <div class="card" v-for="it in pager.items">
        <div class="card-block">
          <router-link :to="{name: 'reading.books.show', params: {id: it.id}}">
            <h4 class="card-title">{{it.title}}</h4>
          </router-link>
          <p class="card-text">{{it.description}}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li :key="k" v-for="k in ['author', 'subject', 'publisher']" class="list-group-item list-group-item-action">
            {{$t(`reading.attributes.book.${k}`)}}: {{it[k]}}
          </li>
          <li class="list-group-item list-group-item-action">{{$t('reading.attributes.book.publishedAt')}}: {{new Date(it.publishedAt).toLocaleDateString()}}</li>
        </ul>
        <div class="card-block">
          <router-link class="btn btn-primary" :to="{name: 'reading.books.show', params: {id: it.id}}">
            {{$t("buttons.view")}}
          </router-link>
        </div>
      </div>
    </div>

  </application-layout>
</template>

<script>
import Application from '@/layouts/Application'
import Pagination from '@/components/Pagination'
import {get} from '@/ajax'

export default {
  name: 'reading-books-index',
  components: {
    'application-layout': Application,
    'pagination-panel': Pagination
  },
  data () {
    return {
      page: null,
      pager: {
        total: 0,
        size: 60
      }
    }
  },
  created () {
    this.fetchData()
  },
  watch: {
    '$route': 'fetchData'
  },
  methods: {
    fetchData () {
      var page = this.$route.params.page
      if (page) {
        get(`/reading/books?page=${page}`).then(function (rst) {
          this.pager = rst
        }.bind(this))
      }
    }
  }
}
</script>
